Settings
Ryder-Project/ryder-app pull request #14
Opened 2024-01-31 06:57 UTC by Harinze

2024-01-31 11:36 UTC, Don-christo requested changes
Good job. LGTM! Please, go through the comments, and tell me what you think, then make the little changes if necessary. After that, re-request my review so that I can approve for merging. Thank you.

2024-01-31 16:19 UTC, Harinze commented on apps/server/src/controllers/riderControllers/editProfileSettings.ts
> +  const userId = req.params.userId;
userId is preferred to id.

2024-01-31 16:19 UTC, Harinze commented on apps/server/src/controllers/riderControllers/editProfileSettings.ts
> +export const editProfile = async (req: Request, res: Response) => {
we are working from ryder dir, pls. u know we have customer dir and ryder dir

2024-01-31 16:19 UTC, Harinze commented on apps/server/src/routes/v1/riders.ts
> +router.put("/editprofile/:userId",  auth, editProfile);
userId is preferred

2024-01-31 16:22 UTC, Harinze commented on apps/Client/src/App.tsx
> +        <Route path="/userprofilesettings" element={<UserprofileSettings />} />
have you seen a url that is camelcased. urls are most of times small cased.   read solid principles ..lolz

2024-01-31 16:22 UTC, Harinze commented on apps/Client/src/routes/Routes.tsx
>          <Route path="/request-rider" element={<RequestRiderPage />} />
url is small cased

2024-01-31 16:26 UTC, Harinze commented on apps/Client/src/App.tsx
> +        <Route path="/userprofilesettings" element={<UserprofileSettings />} />
UserprofileSettings: this is camelcased

2024-01-31 16:27 UTC, Harinze commented on apps/server/src/controllers/riderControllers/editProfileSettings.ts
> +    console.error(error);
ok

2024-02-02 08:00 UTC, Don-christo commented on apps/server/src/routes/v1/riders.ts
> +import {editProfile } from "../../controllers/riderControllers/editProfileSettings"
Yes, that is what you did. I guess you didn't understand what I suggested.

2024-02-02 11:54 UTC, Don-christo approved these changes
Good to go! Well done.

2024-02-02 11:55 UTC, merged