request rider screen
Ryder-Project/ryder-app pull request #3
Opened 2024-01-21 16:40 UTC by Afinjuomo

please kindly review

2024-01-22 14:11 UTC, Don-christo requested changes

2024-01-22 14:11 UTC, Don-christo commented on apps/Client/tailwind.config.js
> +        500: '#ff9900', // Adjust the hex color code as needed
Why the comment? You don't need to adjust the hex color. Find the one suitable and fix there, and remove the comment. The comment is not needed.

2024-01-22 14:11 UTC, Don-christo commented on apps/Client/src/pages/RequestRiderPage.tsx
Making use of react-hook-form should be better than the normal form tag that comes with html.

2024-01-30 13:48 UTC, Afinjuomo reviewed
updated to react hook form

2024-01-30 13:56 UTC, Afinjuomo commented
![Screenshot 2024-01-30 at 10 57 08 AM](https://github.com/Ryder-Project/ryder-app/assets/129465319/f9961935-af47-4da1-a88a-36f26bd33934)

2024-01-30 14:26 UTC, Don-christo approved these changes
Good job. LGTM!

2024-01-30 14:26 UTC, merged