pulled from main
Ryder-Project/ryder-app pull request #38
Opened 2024-02-22 13:39 UTC by Harinze

2024-02-22 13:50 UTC, Don-christo approved these changes
Good job. Thank you. Please remove the comments. There's no use for them, and why are you changing the folder names again? These folder names have been one of the things causing issues. Why changing them again?

2024-02-22 13:50 UTC, Don-christo commented on apps/Client/src/pages/Auth/Login/LoginPage.tsx
> +
Why all the comments? If you're not using it, why not remove it entirely?

2024-02-22 13:57 UTC, Don-christo requested changes
Why are you changing the folder names?

2024-02-22 14:37 UTC, Harinze commented
I was errors with the folder names

2024-02-23 06:26 UTC, Don-christo approved these changes
Good job, boss.

2024-02-23 06:26 UTC, merged