feat: :sparkles: add customer-rider-endpoints
Ryder-Project/ryder-app pull request #4
Opened 2024-01-26 12:00 UTC by Samuel-Adeyeye

Created endpoints to route the user based on either register as a customer or as a rider

2024-01-26 12:01 UTC, Samuel-Adeyeye reviewed
Created endpoints to route the user based on either register as a customer or as a rider.

2024-01-27 00:59 UTC, Don-christo requested changes

2024-01-27 00:59 UTC, Don-christo commented on apps/server/src/controllers/customerController.ts
> +const customers: string[] = [];
We have a database. Why are you using a sample database?

2024-01-27 00:59 UTC, Don-christo commented on apps/server/src/controllers/customerController.ts
> +};
Refactor this whole code by making use of the database models which have been provided. Please make use of existing code in the codebase. This simply means that you did not go through the code base.

2024-01-27 00:59 UTC, Don-christo commented on apps/server/src/controllers/riderController.ts
> +};
The same thing applies to this.

2024-01-27 01:25 UTC, Don-christo requested changes

2024-01-27 01:25 UTC, Don-christo commented on apps/server/package-lock.json
Why did you run your project with npm when we are using yarn? This is wrong. Run your project with yarn please, because that's our package manager.

2024-01-29 04:58 UTC, Samuel-Adeyeye commented on apps/server/package-lock.json
Okay.

2024-01-29 05:32 UTC, closed without merging

2024-01-29 05:32 UTC, Samuel-Adeyeye commented
Resolved